support_tickets/support_tickets/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from tickets import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^tickets/new/$', views.new_ticket, name='new_ticket'),
    url(
        r'^tickets/([a-f0-9]{8}-(?:[a-f0-9]{4}-){3}[a-f0-9]{12})/$',
        views.ticket,
        name='ticket'
    ),
    url(r'^tickets/$', views.tickets_list, name='tickets_list'),
    url(r'^tickets/submitted/$', views.ticket_submitted, name='ticket_submitted'),  # noqa: E501
    url(r'^accounts/', include('allauth.urls')),
    url(r'^account/profile/$', views.user_profile, name='user-profile'),
    url(r'^admin/', admin.site.urls),
]

support_tickets/tickets/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models


class Ticket(models.Model):

    ISSUE_CHOICES = (
        (0, 'Other'),
        (1, 'Issue 1'),
        (2, 'Issue 2'),
        (3, 'Issue 3'),
        (4, 'Issue 4'),
    )

    SEVERITY_CHOICES = (
        (0, 'Low'),
        (1, 'Medium'),
        (2, 'High'),
        (3, 'Critical'),
    )

    issue = models.IntegerField(choices=ISSUE_CHOICES, verbose_name='issue')
    description = models.TextField(verbose_name='description')

    severity = models.IntegerField(
        choices=SEVERITY_CHOICES,
        verbose_name='severity',
    )

    issue_submit_date = models.DateTimeField(
        auto_now=True,
        verbose_name='date submitted',
    )

    uuid = models.UUIDField(
        default=uuid.uuid4,
        unique=True,
        verbose_name='ticket UUID',
    )

    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='ticket owner',
    )

    def __str__(self):
        return f'Ticket {self.uuid}'


class Reply(models.Model):

    date = models.DateTimeField(auto_now=True, verbose_name='date')
    answer = models.TextField(verbose_name='answer')

    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='owner',
    )

    ticket = models.ForeignKey(
        Ticket,
        on_delete=models.CASCADE,
        verbose_name='ticket',
    )

    def __str__(self):
        return f'Reply {self.id}'


class UserProfile(models.Model):

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        verbose_name='user'
    )

support_tickets/tickets/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Reply, Ticket


class TicketForm(forms.ModelForm):

    class Meta:
        model = Ticket
        fields = [
            'issue',
            'severity',
            'description',
        ]


class ReplyForm(forms.ModelForm):

    class Meta:
        model = Reply
        fields = ['answer']


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
        ]

support_tickets/tickets/views.py
import logging

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404, HttpResponse
from django.shortcuts import redirect, render

from tickets.decorators import is_authenticated_and_passes_test
from tickets.forms import ReplyForm, TicketForm, UserForm
from tickets.models import Ticket

logger = logging.getLogger(__name__)


def home(request):
    return render(request, 'base.html', {})


def new_ticket(request):
    form = TicketForm(
        initial={
            'name': f'{request.user.first_name} {request.user.last_name}'
        }
    )
    return render(request, 'tickets/new-ticket.html', {'form': form})


def tickets_list(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = TicketForm(request.POST)
            if form.is_valid():
                ticket = form.save(commit=False)
                ticket.owner = request.user
                ticket.save()
                logger.debug(f'{ticket} created.')
                request.session['ticket-uuid'] = str(ticket.uuid)
                return redirect('ticket_submitted')

        else:
            try:
                if request.user.is_superuser:
                    tickets = Ticket.objects.all()
                else:
                    tickets = Ticket.objects.filter(owner=request.user)
            except:    # noqa: E722
                tickets = None

            return render(
                request,
                'tickets/tickets-list.html',
                {'tickets': tickets}
            )

    else:
        return render(request, 'tickets/tickets-list.html', {})


def ticket_submitted(request):
    try:
        logger.debug('Checking if there is a ticket uuid in session.')
        submitted_ticket_uuid = request.session['ticket-uuid']
        del request.session['ticket-uuid']
        ticket = Ticket.objects.get(uuid=submitted_ticket_uuid)
        logger.debug(f'{ticket} found.')
        return render(request, 'tickets/ticket-submitted.html', {'ticket': ticket})  # noqa: E501

    except KeyError:
        logger.exception('Unable to retrieve ticket UUID of newly created ticket from session')  # noqa: E501
        return redirect('home')

    except ObjectDoesNotExist:
        logger.exception(f'Ticket {submitted_ticket_uuid} not found')
        return redirect('home')


def ticket_ownership(request, uuid):
    try:
        logger.debug(f'Retrieving ticket {uuid}')
        ticket = Ticket.objects.get(uuid=uuid)
    except ObjectDoesNotExist:
        logger.exception(f'Ticket {uuid} not found')
        return False

    if ticket.owner == request.user or request.user.is_superuser:
        return True
    else:
        logger.debug(
            f'Ticket is owned by {ticket.email}, not {request.user.email}.'
        )
        return False


@is_authenticated_and_passes_test(ticket_ownership)
def ticket(request, uuid):
    try:
        ticket = Ticket.objects.get(uuid=uuid)
    except ObjectDoesNotExist:
        logger.exception(f'Ticket {uuid} not found.')
        raise Http404

    if request.method == 'GET':
        ctx = {'ticket': ticket}
        if not ticket.reply_set.all() and request.user.is_superuser:
            ctx['form'] = ReplyForm()

        return render(request, 'tickets/ticket.html', ctx)

    if request.method == 'POST':
        if not request.user.is_superuser:
            return HttpResponse('Unauthorized', status=401)

        form = ReplyForm(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.owner = request.user
            reply.ticket = ticket
            reply.save()
            logger.debug(f'Reply for ticket {ticket.uuid} created')
            return redirect('ticket', ticket.uuid)
        else:
            return HttpResponse('Bad Request', status=400)


@login_required
def user_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        if user_form.is_valid():
            user_form.save()
            messages.success(
                request,
                'Profile updated successfully!',
                extra_tags='profile-updated'
            )
            return redirect('user-profile')
        else:
            return HttpResponse('Bad Request', status=400)
    else:
        user_form = UserForm(instance=request.user)

    return render(request, 'profile/profile-home.html', {'user_form': user_form})  # noqa: E501

support_tickets/tickets/templates/base.html
<!doctype html>
<html lang=en>
<head>
    <meta charset=utf-8>
    <title>
        {% block head_title %}Home{% endblock %}
        {% block extra_head %}{% endblock %}
         &middot; support.liopetas.com
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/tickets/assets/css/main.css">
</head>

<body>
    {% block body %}
        <header>
            {% if request.user.is_authenticated %}
                <nav class="navbar navbar-expand-md navbar-light bg-light">
                    <div class="container">
                        <div class="max-width-container mx-auto">
                            <a class="navbar-brand bold" href="{% url "home" %}">SUPPORT</a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="collapse navbar-collapse" id="navbarToggler">
                                <ul class="navbar-nav mr-auto">
                                    <li class="nav-item active">
                                        <a class="nav-link" href="{% url "tickets_list" %}">Ticket List <span class="sr-only">(current)</span></a>
                                    </li>
                                </ul>
                                <ul class="navbar-nav ml-auto">
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" href="#" id="dropdownUser" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fa fa-bars" aria-hidden="true"></i>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownUser">
                                            <div class="dropdown-item">Signed in as</div>
                                            <h6 class="dropdown-header">
                                                {% if request.user.first_name or request.user.last_name %}
                                                    {{ request.user.first_name }} {{ request.user.last_name }}
                                                {% else %}
                                                    {{ request.user.username }}
                                                {% endif %}
                                            </h6>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" href="{% url "user-profile" %}">Profile</a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" href="{% url "account_logout" %}">Logout</a>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </nav>
            {% else %}
                <nav class="navbar navbar-light bg-light">
                    <div class="container">
                        <div class="max-width-container mx-auto">
                            <a class="navbar-brand bold" href="{% url "home" %}">SUPPORT</a>
                            <div class="nav-item float-right">
                                <a class="btn btn-primary" href="{% url "account_login" %}">Log In</a>
                            </div>
                        </div>
                    </div>
                </nav>
            {% endif %}
        </header>
        <div class="container">
            <div class="max-width-container mx-auto">
                {% block base_content %}
                    <div class="row">
                        <div class="col mx-auto">
                            <div class="main-wrapper">
                                <div class="general-desciption">
                                    <p>
                                        Simple, easy to use and open source support ticket service.
                                        You can find more information and the code on
                                        <a href="https://github.com/KappaLambda/support-tickets">GitHub</a>.
                                    </p>
                                    <p>
                                        Future features:
                                        <li>Registration with facebook account</li>
                                        <li>Tickets manager</li>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endblock %}
                <div class="row">
                    <div class="col mx-auto">
                        <footer>
                            &copy; KappaLambda
                        </footer>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <script src="/static/tickets/assets/js/main.js"></script>

</body>
</html>

support_tickets/tickets/templates/profile/base.html
{% extends 'base.html' %}

{% block base_content %}
    <div class="row">
        <div class="col-8 col-md-6 col-lg-4 mx-auto">
            <div class="main-wrapper">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

support_tickets/tickets/templates/profile/profile-home.html
{% extends 'profile/base.html' %}

{% block head_title %}Your Profile{% endblock %}
{% load bootstrap4 %}

{% block content %}
    <div class="user-profile-wrapper">
        <div class="user-form-wrapper clearfix">
            <form action="{% url "user-profile" %}" method="POST" class="form">
                {% csrf_token %}
                <div class="user-username form-group">
                    <label>Username</label>
                    <input type="text" class="form-control" placeholder="{{ request.user }}" disabled>
                </div>
                <div class="user-email form-group">
                    <label>Email</label>
                    <input type="text" class="form-control" placeholder="{{ request.user.email }}" disabled>
                </div>
                {% bootstrap_form user_form %}
                <button type="submit" class="btn btn-success">Update profile</button>
            </form>
        </div>
        {% if messages %}
            {% for message in messages %}
                {% if 'profile-updated' in message.tags %}
                    <div class="messages-wrapper">
                        <div class="alert alert-success alert-dismissible update-profile-message" role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

support_tickets/tickets/templates/tickets/base.html
{% extends 'base.html' %}

{% block base_content %}
    <div class="row">
        <div class="col mx-auto">
            <div class="main-wrapper">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

support_tickets/tickets/templates/tickets/new-ticket.html
{% extends 'tickets/base.html' %}

{% block head_title %}New Ticket{% endblock %}
{% load bootstrap4 %}

{% block base_content %}
    <div class="row">
        <div class="col-10 col-md-8 col-lg-6 mx-auto">
            <div class="main-wrapper">
                <div class="form-wrapper clearfix">
                    <form action="/tickets/" method="POST">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col">
                                {% bootstrap_field form.issue %}
                            </div>
                            <div class="col">
                                {% bootstrap_field form.severity %}
                            </div>
                        </div>
                        {% bootstrap_field form.description placeholder="Give us more information about your issue" %}
                        <div class="submit-ticket">
                            {% bootstrap_button "Submit" button_type="submit" button_class="btn-primary float-right" %}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

support_tickets/tickets/templates/tickets/ticket-submitted.html
{% extends 'tickets/base.html' %}

{% block head_title %}Ticket Submitted{% endblock %}

{% block content %}
    <h6>Thank you {{ ticket.name }}</h6>
    <div>
        You ticket has been submitted.
        To view more details about your ticket click
        <a href="{% url 'ticket' ticket.uuid %}">here</a>.
    </div>
{% endblock %}

support_tickets/tickets/templates/tickets/ticket.html
{% extends 'tickets/base.html' %}

{% block head_title %}Ticket {{ ticket.id }}{% endblock %}

{% load bootstrap4 %}

{% block content %}
    <div class="ticket-info-wrapper">
        <div class="ticket-info-title">
            <div class="h3">Ticket {{ ticket.id }}</div>
            <div class="ticket-info main">
                <span class="ticket-info-has-reply">
                    {% if ticket.reply_set.all %}
                        <span class="badge badge-success">Has reply</span>
                    {% else %}
                        <span class="badge badge-danger">No reply</span>
                    {% endif %}
                </span>
                <span class="ticket-info-issue"> &middot; {{ ticket.get_issue_display }}</span>
                <span class="ticket-info-severity"> &middot; {{ ticket.get_severity_display }}</span>
            </div>
        </div>
        <div class="ticket-box">
            <div class="ticket-box-head">
                <span class="ticket-info-name"><strong>{{ ticket.name }}</strong></span>
                <span class="ticket-info-date">submitted on {{ ticket.issue_submit_date }}</span>
            </div>
            <div class="ticket-box-main">
                <span class="ticket-info-description">{{ ticket.description }}</span>
            </div>
        </div>
    </div>
    {% if ticket.reply_set.all %}
        {% for reply in ticket.reply_set.all %}
            <div class="ticket-reply-wrapper">
                <div class="ticket-box">
                    <div class="ticket-box-head">
                        <span class="ticket-info-name"><strong>{{ reply.owner.first_name }} {{ reply.owner.last_name }}</strong></span>
                        <span class="ticket-info-date">submitted on {{ reply.date }}</span>
                    </div>
                    <div class="ticket-box-main">
                        <span class="ticket-info-description">{{ reply.answer }}</span>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        {% if form %}
            <div class="reply-form-box">
                <div class="reply-form-head">
                    <span class="ticket-info-name"><strong>{{ request.user }}</strong></span>
                </div>
                <div class="reply-form-wrapper clearfix">
                    <form action="{% url 'ticket' ticket.uuid %}" method="POST">
                        {% csrf_token %}
                        {% bootstrap_form form layout="inline" %}
                        {% buttons %}
                            <button type="submit" class="btn btn-success float-right">Reply</button>
                        {% endbuttons %}
                    </form>
                </div>
            </div>
        {% endif %}
    {% endif %}
{% endblock %}

support_tickets/tickets/templates/tickets/tickets-list.html
{% extends 'tickets/base.html' %}

{% block head_title %}Tickets List{% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
        <div class="new-ticket-button clearfix">
            <a class="btn btn-success float-right" href="{% url 'new_ticket' %}">New ticket</a>
        </div>
        <div class="tickets-list">
            {% if tickets %}
                <table class="table table-hover">
                    <thead class="table-secondary">
                        <tr>
                            <th>Replied</th>
                            <th>Ticket</th>
                            <th>Issue</th>
                            <th>Severity</th>
                            <th>Date Submitted</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for ticket in tickets %}
                        <tr class="clickable-row" href="{% url 'ticket' ticket.uuid %}">
                            <td>
                                {% if ticket.reply_set.all %}
                                <i class="fa fa-check-circle text-success" aria-hidden="true"></i>
                                {% else %}
                                <i class="fa fa-times-circle text-danger" aria-hidden="true"></i>
                                {% endif %}
                            </td>
                            <td>{{ ticket.id }}</td>
                            <td>{{ ticket.get_issue_display }}</td>
                            <td>{{ ticket.get_severity_display }}</td>
                            <td>{{ ticket.issue_submit_date }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                There are no tickets.
            {% endif %}
        </div>
    {% else %}
        <div class="login-message">
            Sign in to your account to manage your tickets.
        </div>
    {% endif %}
{% endblock %}